name: Default CI Workflow

on: [ push,pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: lint
          gradle-version: wrapper
          gradle-dependencies-cache-key: gradle/libs.versions.toml
          arguments: app:lintDebug
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: Build
        with:
          job-id: build
          gradle-version: wrapper
          gradle-dependencies-cache-key: gradle/libs.versions.toml
          arguments: :app:assembleDebug :app:assembleDebugUnitTest :app:assembleDebugAndroidTest
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: testDebugUnitTest
        with:
          job-id: build
          gradle-version: wrapper
          gradle-dependencies-cache-key: gradle/libs.versions.toml
          arguments: app:testDebugUnitTest