name: Default CI Workflow

on: [ push,pull_request ]

env:
  TERM: dumb

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: lint
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: app:lintDebug spotlessCheck
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: build
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: :app:assembleDebug --scan
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: unit-tests
        with:
          debug: false
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: app:testDebugUnitTest --scan
  build-logic:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: burrunan/gradle-cache-action@v1
        name: build-logic
        with:
          debug: false
          job-id: build-logic
          read-only: ${{ github.ref != 'refs/heads/main' }}
          build-root-directory: build-logic
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: build