name: Default CI Workflow

on: [ push,pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: lint
        with:
          job-id: lint
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: app:lintDebug spotlessCheck
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: build
        with:
          job-id: build
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: :app:assembleDebug --scan
  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: burrunan/gradle-cache-action@v1
        name: unit-tests
        with:
          job-id: unit-tests
          read-only: ${{ github.ref != 'refs/heads/main' }}
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
            build-logic/**/Constants.kt
          arguments: app:testDebugUnitTest --scan