name: Docker Workflow

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docker.yml'
      - 'docker/**'
      - 'gradle**'
      - '**.gradle'
      - '**.gradle.kts'
      - 'gradle.properties'
      - 'build-logic/**/Constants.kt'

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Set Gradle permissions
        run: sudo chmod +x ./gradlew

      - name: Prepare Gradle
        run: |
          cd docker
          export GRADLE_USER_HOME="$(pwd)/cache/.gradle"
          cd ..
          ./gradlew --version --no-daemon -g $GRADLE_USER_HOME
          ./gradlew resolveDependencies --no-daemon -g $GRADLE_USER_HOME
          find $GRADLE_USER_HOME -name "*.lock" -type f -delete
          find $GRADLE_USER_HOME -name "gc.properties" -type f -delete

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: docker
          dockerfile: Dockerfile